"""One sample row per replicated table (except the audit chain), for replication and ingest tests."""

from __future__ import annotations

from datetime import UTC, datetime

from app.storage.models import (
    Base,
    BreakerEventRow,
    BreakerStateRow,
    ConfigSnapshot,
    DecisionCheckRow,
    DecisionRecordRow,
    KillSwitchEvent,
    OrderIntentRow,
    PaperAccountRow,
    PaperIntentRow,
    PaperPositionRow,
    RiskBaseline,
    RiskDeal,
    RiskState,
    Run,
)

T = datetime(2026, 9, 30, 10, 0, tzinfo=UTC)


def sample_rows() -> list[Base]:
    return [
        DecisionRecordRow(
            decision_id="d1",
            created_at=T,
            signal_id="s1",
            idempotency_key="k1",
            strategy="example_trend_pullback",
            symbol="EURUSD",
            timeframe="M15",
            action="BUY",
            profile="EXECUTION",
            decision="ACCEPT",
            reason_codes=[],
            warnings=["DEMO_UNPROVEN"],
            volume=0.1,
            risk_money=5.0,
            entry_price=1.1,
            stop_loss=1.095,
            take_profit=1.11,
            plan=[{"part": 0, "volume": 0.1}],
            bar_times={"M15": T.isoformat()},
            signal={"score": 0.7},
            market={"spread": 1.2},
            config_hash="c" * 32,
            code_version="0.1.0",
        ),
        DecisionCheckRow(
            decision_id="d1",
            seq=0,
            name="spread",
            reason="OK",
            passed=True,
            kind="HARD",
            value=1.2,
            threshold=3,
        ),
        OrderIntentRow(
            intent_id="i1",
            idempotency_key="k1:0",
            decision_id="d1",
            signal_id="s1",
            strategy="example_trend_pullback",
            symbol="EURUSD",
            side="BUY",
            volume=0.1,
            price_requested=1.1,
            sl=1.095,
            tp=1.11,
            magic=7_310_000,
            comment="taa",
            risk_money=5.0,
            state="FILLED",
            attempts=1,
            retcode=10009,
            retcode_desc="DONE",
            order_ticket=1,
            deal_ticket=2,
            position_ticket=3,
            fill_price=1.1001,
            fill_volume=0.1,
            slippage_points=1.0,
            expires_at=T,
            sent_at=T,
            created_at=T,
            updated_at=T,
            detail="",
        ),
        PaperAccountRow(
            account_key="acct",
            currency="USD",
            initial_balance=1000.0,
            balance=1000.0,
            created_at=T,
            updated_at=T,
        ),
        PaperIntentRow(
            intent_id="p1",
            account_key="acct",
            idempotency_key="k1:0",
            decision_id="d1",
            signal_id="s1",
            strategy="example_trend_pullback",
            symbol="EURUSD",
            side="BUY",
            volume=0.1,
            entry_type="MARKET",
            price=None,
            sl=1.095,
            tp=1.11,
            expires_at=T,
            magic=7_310_000,
            risk_money=5.0,
            order_id=1,
            ticket=10,
            status="FILLED",
            created_at=T,
            updated_at=T,
        ),
        PaperPositionRow(
            ticket=10,
            account_key="acct",
            intent_id="p1",
            symbol="EURUSD",
            side="BUY",
            volume=0.1,
            entry_time=T,
            entry_price=1.1,
            sl=1.095,
            tp=1.11,
            stop_kind="INITIAL",
            status="OPEN",
            updated_at=T,
        ),
        BreakerStateRow(name="DAILY_LOSS", scope_key="", state="CLOSED", updated_at=T),
        BreakerEventRow(
            ts_utc=T, name="DAILY_LOSS", action="TRIP", severity="CRITICAL", actor="engine", reason="limit"
        ),
        KillSwitchEvent(ts_utc=T, action="ACTIVATE", mode="HALT", source="cli", actor="owner", reason="test"),
        RiskDeal(account_key="acct", ticket=2**40, kind="CLOSE", amount=-5.0, time_utc=T),
        RiskState(account_key="acct", hwm=1000.0, updated_at=T),
        RiskBaseline(account_key="acct", period="DAY", period_key="2026-09-30", start_equity=1000.0),
        Run(run_id="r1", process="engine", mode="PAPER", version="0.1.0", config_hash="c" * 32),
        ConfigSnapshot(config_hash="c" * 32, payload={"env": {"MT5_PASSWORD": "***set***"}}),
    ]
