"""One sample row per replicated table (except the audit chain), for replication and ingest tests."""

from __future__ import annotations

from datetime import UTC, datetime

from app.storage.models import (
    AIAssessmentRow,
    AINoteRow,
    Base,
    BreakerEventRow,
    BreakerStateRow,
    BrokerTradeRow,
    CalibrationTableRow,
    ConfigSnapshot,
    DecisionCheckRow,
    DecisionRecordRow,
    EvidenceModelVersionRow,
    KillSwitchEvent,
    ManualTradeLinkRow,
    OpportunityRow,
    OrderIntentRow,
    PaperAccountRow,
    PaperIntentRow,
    PaperPositionRow,
    RiskBaseline,
    RiskDeal,
    RiskState,
    Run,
    ShadowTradeRow,
    SuitabilitySnapshotRow,
    SymbolCatalogRow,
)

T = datetime(2026, 9, 30, 10, 0, tzinfo=UTC)


def sample_rows() -> list[Base]:
    return [
        DecisionRecordRow(
            decision_id="d1",
            created_at=T,
            signal_id="s1",
            idempotency_key="k1",
            strategy="example_trend_pullback",
            symbol="EURUSD",
            timeframe="M15",
            action="BUY",
            profile="EXECUTION",
            decision="ACCEPT",
            reason_codes=[],
            warnings=["DEMO_UNPROVEN"],
            volume=0.1,
            risk_money=5.0,
            entry_price=1.1,
            stop_loss=1.095,
            take_profit=1.11,
            plan=[{"part": 0, "volume": 0.1}],
            bar_times={"M15": T.isoformat()},
            signal={"score": 0.7},
            market={"spread": 1.2},
            config_hash="c" * 32,
            code_version="0.1.0",
            risk_source="cloud:367a33e42c836f3d",
            risk_percent=0.5,
        ),
        DecisionCheckRow(
            decision_id="d1",
            seq=0,
            name="spread",
            reason="OK",
            passed=True,
            kind="HARD",
            value=1.2,
            threshold=3,
        ),
        OrderIntentRow(
            intent_id="i1",
            idempotency_key="k1:0",
            decision_id="d1",
            signal_id="s1",
            strategy="example_trend_pullback",
            symbol="EURUSD",
            side="BUY",
            volume=0.1,
            price_requested=1.1,
            sl=1.095,
            tp=1.11,
            magic=7_310_000,
            comment="taa",
            risk_money=5.0,
            state="FILLED",
            attempts=1,
            retcode=10009,
            retcode_desc="DONE",
            order_ticket=1,
            deal_ticket=2,
            position_ticket=3,
            fill_price=1.1001,
            fill_volume=0.1,
            slippage_points=1.0,
            expires_at=T,
            sent_at=T,
            created_at=T,
            updated_at=T,
            detail="",
        ),
        PaperAccountRow(
            account_key="acct",
            currency="USD",
            initial_balance=1000.0,
            balance=1000.0,
            created_at=T,
            updated_at=T,
        ),
        PaperIntentRow(
            intent_id="p1",
            account_key="acct",
            idempotency_key="k1:0",
            decision_id="d1",
            signal_id="s1",
            strategy="example_trend_pullback",
            symbol="EURUSD",
            side="BUY",
            volume=0.1,
            entry_type="MARKET",
            price=None,
            sl=1.095,
            tp=1.11,
            expires_at=T,
            magic=7_310_000,
            risk_money=5.0,
            order_id=1,
            ticket=10,
            status="FILLED",
            created_at=T,
            updated_at=T,
        ),
        PaperPositionRow(
            ticket=10,
            account_key="acct",
            intent_id="p1",
            symbol="EURUSD",
            side="BUY",
            volume=0.1,
            entry_time=T,
            entry_price=1.1,
            sl=1.095,
            tp=1.11,
            stop_kind="SL",  # ExitReason.STOP_LOSS: the initial stop
            status="OPEN",
            updated_at=T,
        ),
        BreakerStateRow(name="DAILY_LOSS", scope_key="", state="CLOSED", updated_at=T),
        BreakerEventRow(
            ts_utc=T, name="DAILY_LOSS", action="TRIP", severity="CRITICAL", actor="engine", reason="limit"
        ),
        KillSwitchEvent(ts_utc=T, action="ACTIVATE", mode="HALT", source="cli", actor="owner", reason="test"),
        RiskDeal(account_key="acct", ticket=2**40, kind="CLOSE", amount=-5.0, time_utc=T),
        RiskState(account_key="acct", hwm=1000.0, updated_at=T),
        RiskBaseline(account_key="acct", period="DAY", period_key="2026-09-30", start_equity=1000.0),
        Run(run_id="r1", process="engine", mode="PAPER", version="0.1.0", config_hash="c" * 32),
        ConfigSnapshot(config_hash="c" * 32, payload={"env": {"MT5_PASSWORD": "***set***"}}),
        SymbolCatalogRow(
            server="FBS-Demo",
            symbol="EURUSD",
            asset_class="FX_MAJOR",
            enabled=True,
            reason="",
            path="Forex\\EURUSD",
            description="Euro vs US Dollar",
            spec={"digits": 5},
            first_seen_at=T,
            refreshed_at=T,
            present=True,
        ),
        SuitabilitySnapshotRow(
            server="FBS-Demo",
            symbol="EURUSD",
            hour=T,
            computed_at=T,
            asset_class="FX_MAJOR",
            rank=1,
            eligible=True,
            overall=82.5,
            now_score=70.0,
            failed_gates=[],
            payload={"scores": {"S1": 90.0}},
        ),
        AIAssessmentRow(
            assessment_id="a1",
            created_at=T,
            signal_key="k1",
            symbol="EURUSD",
            strategy="example_trend_pullback",
            side="BUY",
            bar_close_utc=T.isoformat(),
            mode="veto",
            status="OK",
            verdict="AGREE",
            confidence=80,
            reasons=["H1 trend agrees"],
            model="claude-opus-5-5",
            input_tokens=1200,
            output_tokens=300,
            cost_usd=0.0108,
            latency_ms=2400.0,
            effect="PASSED",
            detail="",
        ),
        AINoteRow(
            note_id="OPPORTUNITY:k1",
            kind="OPPORTUNITY",
            subject="k1",
            created_at=T,
            status="OK",
            verdict="AGREE",
            confidence=66,
            reasons=["H1 trend agrees with the BUY"],
            text_en="The pullback entry agrees with the higher-timeframe trend evidence.",
            text_th="จุดเข้าหลังการย่อตัวสอดคล้องกับหลักฐานแนวโน้มใน timeframe ใหญ่",
            facts={"subject": "k1", "score": 0.7},
            model="claude-opus-5-5",
            input_tokens=900,
            output_tokens=250,
            cost_usd=0.0086,
            latency_ms=1200.0,
            detail="",
        ),
        BrokerTradeRow(
            position_ticket=2079981852,
            account_key="acc",
            mode="DEMO",
            intent_id="bi1",
            decision_id="d1",
            strategy="example_trend_pullback",
            magic=7310002,
            symbol="EURUSD",
            side="BUY",
            volume=0.07,
            plan_key="",
            part_index=0,
            entry_time=T,
            entry_price=1.1002,
            sl_initial=1.0982,
            tp=1.1042,
            exit_time=T,
            exit_price=1.0982,
            exit_reason="SL",
            profit=-14.0,
            swap=-0.12,
            commission=0.0,
            net=-14.12,
            r_multiple=-1.0,
            booked_at=T,
        ),
        ManualTradeLinkRow(
            position_id=2078278005,
            ticket=2078278005,
            symbol="EURUSD",
            side="BUY",
            volume=0.1,
            price_open=1.1002,
            opened_at=T,
            confidence="HIGH",
            signal_key="k1",
            strategy="example_trend_pullback",
            decision_id="d1",
            opportunity_id="k1",
            score=0.8,
            distance_r=0.04,
            candidates=1,
            rule_version="1",
            matched_at=T,
        ),
        OpportunityRow(
            opportunity_id="k1",
            server="FBS-Demo",
            strategy="example_trend_pullback",
            symbol="EURUSD",
            asset_class="FX_MAJOR",
            timeframe="M15",
            side="BUY",
            bar_close_at=T,
            created_at=T,
            signal_expires_at=T,
            entry=1.1,
            stop_loss=1.095,
            take_profit=1.11,
            rr=2.0,
            setup_strength=72.0,
            score=0.7,
            status="CANDIDATE",
            status_reason="",
            status_at=T,
            valid_until=None,
            valid_reason="",
            alerted_at=None,
            decision_id="d1",
            warnings=[],
            lot=0.1,
            risk_money=5.0,
            reward_money=10.0,
            equity=1000.0,
            currency="USD",
            session="LONDON",
            regime="TREND",
            atr=0.001,
            spread_points=12.0,
            bid=1.1,
            ask=1.10012,
            quote_at=T,
            requirements_version="r" * 16,
            calibration_version=None,
            features={"trend.ema": 1.0},
            signal={"conditions": []},
        ),
        ShadowTradeRow(
            shadow_id="k1:PLAN",
            opportunity_id="k1",
            variant="PLAN",
            source="LIVE",
            server="FBS-Demo",
            strategy="example_trend_pullback",
            symbol="EURUSD",
            asset_class="FX_MAJOR",
            timeframe="M15",
            side="BUY",
            session="LONDON",
            setup_strength=72.0,
            rr=2.0,
            features={"trend.ema": 1.0},
            atr=0.001,
            alerted=False,
            followed=False,
            status="OPEN",
            signal_at=T,
            created_at=T,
            updated_at=T,
            entry_at=T,
            entry_price=1.10012,
            bid=1.1,
            ask=1.10012,
            spread_points=12.0,
            slippage_points=0.0,
            initial_sl=1.095,
            sl=1.095,
            tp=1.11,
            stop_kind="SL",
            deadline=T,
            cursor=T,
            lot=0.1,
            equity=1000.0,
            currency="USD",
            flags=[],
        ),
        CalibrationTableRow(
            version="20260930T100000-abcdef",
            server="FBS-Demo",
            built_at=T,
            variant="PLAN",
            n_live=10,
            n_replay=40,
            window_start=None,
            window_end=T,
            params={"kappa": 20},
            cells=[],
            cv={"selected": "buckets"},
            uses_evidence=False,
            brier=0.24,
            reliability=[],
        ),
        EvidenceModelVersionRow(
            version="20260930T100000-abcdef",
            server="FBS-Demo",
            built_at=T,
            pooled=True,
            group_key=[],
            names=["trend.ema"],
            coef=[0.3],
            intercept=-0.1,
            means=[0.5],
            active=[0.6],
            l2=1.0,
            n=50,
        ),
    ]
