"""Decision reason codes (PLAN §A8). One enum shared by sizing, exposure, breakers and the decision engine.

Codes are stable identifiers: they are persisted, replicated to the cloud and translated in the PWA
(``reason.<code>``). Parameterized codes (``BREAKER_OPEN:<name>``, ``ORDER_CHECK_FAILED:<retcode>``) are built
with :func:`with_detail`.
"""

from __future__ import annotations

from enum import StrEnum


class Reason(StrEnum):
    # system
    KILL_SWITCH_ACTIVE = "KILL_SWITCH_ACTIVE"
    BREAKER_OPEN = "BREAKER_OPEN"
    BROKER_UNHEALTHY = "BROKER_UNHEALTHY"
    STORAGE_UNHEALTHY = "STORAGE_UNHEALTHY"
    CLOCK_UNVERIFIED = "CLOCK_UNVERIFIED"
    # mode
    ORDERS_NOT_ALLOWED_IN_MODE = "ORDERS_NOT_ALLOWED_IN_MODE"
    LIVE_GATE_FAILED = "LIVE_GATE_FAILED"
    # symbol
    SYMBOL_NOT_ALLOWED = "SYMBOL_NOT_ALLOWED"
    SYMBOL_UNAVAILABLE = "SYMBOL_UNAVAILABLE"
    SYMBOL_TRADE_DISABLED = "SYMBOL_TRADE_DISABLED"
    DIRECTION_NOT_ALLOWED = "DIRECTION_NOT_ALLOWED"
    # data
    DATA_STALE = "DATA_STALE"
    DATA_GAPS = "DATA_GAPS"
    DATA_INVALID = "DATA_INVALID"
    SIGNAL_EXPIRED = "SIGNAL_EXPIRED"
    PRICE_DRIFT = "PRICE_DRIFT"
    # session
    SESSION_CLOSED = "SESSION_CLOSED"
    MARKET_CLOSED = "MARKET_CLOSED"
    NEWS_BLACKOUT = "NEWS_BLACKOUT"
    # costs
    SPREAD_TOO_HIGH = "SPREAD_TOO_HIGH"
    SPREAD_TO_SL_TOO_HIGH = "SPREAD_TO_SL_TOO_HIGH"
    EXPECTED_SLIPPAGE_TOO_HIGH = "EXPECTED_SLIPPAGE_TOO_HIGH"
    # signal geometry
    SL_MISSING = "SL_MISSING"
    TP_MISSING = "TP_MISSING"
    SL_WRONG_SIDE = "SL_WRONG_SIDE"
    SL_TOO_CLOSE = "SL_TOO_CLOSE"
    SL_TOO_FAR = "SL_TOO_FAR"
    RR_TOO_LOW = "RR_TOO_LOW"
    # AI (M2)
    AI_DISAGREES = "AI_DISAGREES"
    AI_LOW_CONFIDENCE = "AI_LOW_CONFIDENCE"
    AI_UNAVAILABLE = "AI_UNAVAILABLE"
    # portfolio
    MAX_OPEN_POSITIONS = "MAX_OPEN_POSITIONS"
    MAX_POSITIONS_PER_SYMBOL = "MAX_POSITIONS_PER_SYMBOL"
    CONFLICTING_POSITION = "CONFLICTING_POSITION"
    DUPLICATE_SIGNAL = "DUPLICATE_SIGNAL"
    PENDING_INTENT_EXISTS = "PENDING_INTENT_EXISTS"
    CORRELATION_LIMIT = "CORRELATION_LIMIT"
    CURRENCY_EXPOSURE_LIMIT = "CURRENCY_EXPOSURE_LIMIT"
    MAX_TOTAL_OPEN_RISK = "MAX_TOTAL_OPEN_RISK"
    UNKNOWN_POSITION_RISK = "UNKNOWN_POSITION_RISK"
    FOREIGN_POSITIONS = "FOREIGN_POSITIONS"  # foreign_positions_policy=halt and a manual position is open
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    # account
    DAILY_LOSS_LIMIT = "DAILY_LOSS_LIMIT"
    WEEKLY_LOSS_LIMIT = "WEEKLY_LOSS_LIMIT"
    MAX_DRAWDOWN = "MAX_DRAWDOWN"
    CONSECUTIVE_LOSSES = "CONSECUTIVE_LOSSES"
    MARGIN_INSUFFICIENT = "MARGIN_INSUFFICIENT"
    MARGIN_LEVEL_TOO_LOW = "MARGIN_LEVEL_TOO_LOW"
    LEVERAGE_LIMIT = "LEVERAGE_LIMIT"
    # sizing
    SYMBOL_SPEC_INCONSISTENT = "SYMBOL_SPEC_INCONSISTENT"
    RISK_BELOW_MIN_LOT = "RISK_BELOW_MIN_LOT"
    VOLUME_INVALID = "VOLUME_INVALID"
    # broker precheck (M2)
    ORDER_CHECK_FAILED = "ORDER_CHECK_FAILED"


def with_detail(reason: Reason, detail: str | int) -> str:
    """``BREAKER_OPEN:DAILY_LOSS``-style codes."""
    return f"{reason.value}:{detail}"
