"""phase0 system tables

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 16:33:40.768629
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_chain_heads',
    sa.Column('chain', sa.String(length=64), nullable=False),
    sa.Column('last_seq', sa.Integer(), nullable=False),
    sa.Column('last_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('chain', name=op.f('pk_audit_chain_heads'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('chain', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts_utc', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('chain', 'seq', name='uq_audit_events_chain_seq'),
    sa.UniqueConstraint('event_id', name=op.f('uq_audit_events_event_id')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_events_hash'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_chain'), ['chain'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_ts_utc'), ['ts_utc'], unique=False)

    op.create_table('config_snapshots',
    sa.Column('config_hash', sa.String(length=32), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('config_hash', name=op.f('pk_config_snapshots'))
    )
    op.create_table('kill_switch_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_utc', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kill_switch_events'))
    )
    with op.batch_alter_table('kill_switch_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kill_switch_events_ts_utc'), ['ts_utc'], unique=False)

    op.create_table('runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('process', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('config_hash', sa.String(length=32), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('started_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('ended_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    with op.batch_alter_table('kill_switch_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kill_switch_events_ts_utc'))

    op.drop_table('kill_switch_events')
    op.drop_table('config_snapshots')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_ts_utc'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_chain'))

    op.drop_table('audit_events')
    op.drop_table('audit_chain_heads')
    # ### end Alembic commands ###
