"""phase1 market data tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 16:47:09.633571
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_candles',
    sa.Column('server', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open_time', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('time_server', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('tick_volume', sa.BigInteger(), nullable=False),
    sa.Column('spread', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('server', 'symbol', 'timeframe', 'open_time', name=op.f('pk_history_candles'))
    )
    op.create_table('processed_candles',
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('last_open_time_utc', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'timeframe', name=op.f('pk_processed_candles'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_candles')
    op.drop_table('history_candles')
    # ### end Alembic commands ###
