"""phase4 risk tables

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 20:39:04.324245
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_baselines',
    sa.Column('account_key', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=8), nullable=False),
    sa.Column('period_key', sa.String(length=16), nullable=False),
    sa.Column('start_equity', sa.Float(), nullable=False),
    sa.Column('cash_flow', sa.Float(), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_key', 'period', 'period_key', name=op.f('pk_risk_baselines'))
    )
    op.create_table('risk_deals',
    sa.Column('account_key', sa.String(length=32), nullable=False),
    sa.Column('ticket', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('time_utc', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_key', 'ticket', name=op.f('pk_risk_deals'))
    )
    with op.batch_alter_table('risk_deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_deals_time_utc'), ['time_utc'], unique=False)

    op.create_table('risk_state',
    sa.Column('account_key', sa.String(length=32), nullable=False),
    sa.Column('hwm', sa.Float(), nullable=False),
    sa.Column('cumulative_cash_flow', sa.Float(), nullable=False),
    sa.Column('consecutive_losses', sa.Integer(), nullable=False),
    sa.Column('last_loss_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_key', name=op.f('pk_risk_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_state')
    with op.batch_alter_table('risk_deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_deals_time_utc'))

    op.drop_table('risk_deals')
    op.drop_table('risk_baselines')
    # ### end Alembic commands ###
