"""phase4 circuit breakers

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 20:42:06.397689
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breaker_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_utc', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_breaker_events'))
    )
    with op.batch_alter_table('breaker_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breaker_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_breaker_events_ts_utc'), ['ts_utc'], unique=False)

    op.create_table('breaker_states',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('scope_key', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('latched', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('opened_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('opened_day_key', sa.String(length=16), nullable=False),
    sa.Column('opened_week_key', sa.String(length=16), nullable=False),
    sa.Column('trips_day_key', sa.String(length=16), nullable=False),
    sa.Column('trips_today', sa.Integer(), nullable=False),
    sa.Column('healthy_count', sa.Integer(), nullable=False),
    sa.Column('healthy_since', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'scope_key', name=op.f('pk_breaker_states'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breaker_states')
    with op.batch_alter_table('breaker_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breaker_events_ts_utc'))
        batch_op.drop_index(batch_op.f('ix_breaker_events_name'))

    op.drop_table('breaker_events')
    # ### end Alembic commands ###
