"""phase4 decision records

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-03 20:52:54.182866
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('threshold', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_checks'))
    )
    with op.batch_alter_table('decision_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_checks_decision_id'), ['decision_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_checks_reason'), ['reason'], unique=False)

    op.create_table('decision_records',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('profile', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('risk_money', sa.Float(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('bar_times', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('signal', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('market', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('config_hash', sa.String(length=32), nullable=False),
    sa.Column('code_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_decision_records'))
    )
    with op.batch_alter_table('decision_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decision_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_decision_records_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_records_symbol'))
        batch_op.drop_index(batch_op.f('ix_decision_records_signal_id'))
        batch_op.drop_index(batch_op.f('ix_decision_records_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_decision_records_decision'))
        batch_op.drop_index(batch_op.f('ix_decision_records_created_at'))

    op.drop_table('decision_records')
    with op.batch_alter_table('decision_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decision_checks_reason'))
        batch_op.drop_index(batch_op.f('ix_decision_checks_decision_id'))

    op.drop_table('decision_checks')
    # ### end Alembic commands ###
