"""phase6 paper book

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-03 21:31:43.916127
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('account_key', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('next_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('account_key', name=op.f('pk_paper_accounts'))
    )
    op.create_table('paper_intents',
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('account_key', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('entry_type', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('expires_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('magic', sa.BigInteger(), nullable=False),
    sa.Column('risk_money', sa.Float(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('intent_id', name=op.f('pk_paper_intents')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_paper_intents_idempotency_key'))
    )
    with op.batch_alter_table('paper_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_intents_account_key'), ['account_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_intents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_intents_symbol'), ['symbol'], unique=False)

    op.create_table('paper_positions',
    sa.Column('ticket', sa.BigInteger(), nullable=False),
    sa.Column('account_key', sa.String(length=32), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('entry_time', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('stop_kind', sa.String(length=8), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('swap', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('mfe', sa.Float(), nullable=False),
    sa.Column('price_current', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('exit_time', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=16), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('net', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('bars_held', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ticket', name=op.f('pk_paper_positions'))
    )
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_positions_account_key'), ['account_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_positions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_positions_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_paper_positions_status'))
        batch_op.drop_index(batch_op.f('ix_paper_positions_account_key'))

    op.drop_table('paper_positions')
    with op.batch_alter_table('paper_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_intents_symbol'))
        batch_op.drop_index(batch_op.f('ix_paper_intents_status'))
        batch_op.drop_index(batch_op.f('ix_paper_intents_account_key'))

    op.drop_table('paper_intents')
    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
