"""phase12 order intents

Revision ID: 0008
Revises: 0007
Create Date: 2026-10-03 22:15:00.514349
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_intents',
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('price_requested', sa.Float(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=False),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('magic', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.String(length=32), nullable=False),
    sa.Column('risk_money', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('retcode', sa.Integer(), nullable=True),
    sa.Column('retcode_desc', sa.String(length=48), nullable=False),
    sa.Column('order_ticket', sa.BigInteger(), nullable=True),
    sa.Column('deal_ticket', sa.BigInteger(), nullable=True),
    sa.Column('position_ticket', sa.BigInteger(), nullable=True),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('fill_volume', sa.Float(), nullable=True),
    sa.Column('slippage_points', sa.Float(), nullable=True),
    sa.Column('expires_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('sent_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('intent_id', name=op.f('pk_order_intents')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_order_intents_idempotency_key'))
    )
    with op.batch_alter_table('order_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_intents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_intents_position_ticket'), ['position_ticket'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_intents_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_intents_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_intents_symbol'))
        batch_op.drop_index(batch_op.f('ix_order_intents_state'))
        batch_op.drop_index(batch_op.f('ix_order_intents_position_ticket'))
        batch_op.drop_index(batch_op.f('ix_order_intents_created_at'))

    op.drop_table('order_intents')
    # ### end Alembic commands ###
