"""phase6a symbol catalog

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-03 23:39:25.990308
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol_catalog',
    sa.Column('server', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('first_seen_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('refreshed_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('server', 'symbol', name=op.f('pk_symbol_catalog'))
    )
    with op.batch_alter_table('symbol_catalog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_symbol_catalog_asset_class'), ['asset_class'], unique=False)
        batch_op.create_index(batch_op.f('ix_symbol_catalog_refreshed_at'), ['refreshed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symbol_catalog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_symbol_catalog_refreshed_at'))
        batch_op.drop_index(batch_op.f('ix_symbol_catalog_asset_class'))

    op.drop_table('symbol_catalog')
    # ### end Alembic commands ###
