"""phase6a suitability snapshots

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-04 00:05:16.745781
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suitability_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('hour', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('computed_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('now_score', sa.Float(), nullable=False),
    sa.Column('failed_gates', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suitability_snapshots')),
    sa.UniqueConstraint('server', 'symbol', 'hour', name='uq_suitability_symbol_hour')
    )
    with op.batch_alter_table('suitability_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suitability_snapshots_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suitability_snapshots_hour'), ['hour'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suitability_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suitability_snapshots_hour'))
        batch_op.drop_index(batch_op.f('ix_suitability_snapshots_computed_at'))

    op.drop_table('suitability_snapshots')
    # ### end Alembic commands ###
