"""phase6b opportunities

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-04 01:04:20.803103
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0011'
down_revision: str | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('opportunity_id', sa.String(length=64), nullable=False),
    sa.Column('server', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('bar_close_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('signal_expires_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('rr', sa.Float(), nullable=True),
    sa.Column('setup_strength', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=False),
    sa.Column('status_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('valid_until', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('valid_reason', sa.String(length=64), nullable=False),
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('lot', sa.Float(), nullable=True),
    sa.Column('risk_money', sa.Float(), nullable=True),
    sa.Column('reward_money', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('session', sa.String(length=24), nullable=False),
    sa.Column('regime', sa.String(length=16), nullable=False),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('spread_points', sa.Float(), nullable=True),
    sa.Column('requirements_version', sa.String(length=16), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('signal', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('opportunity_id', name=op.f('pk_opportunities'))
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_bar_close_at'), ['bar_close_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_server'), ['server'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_symbol'))
        batch_op.drop_index(batch_op.f('ix_opportunities_status'))
        batch_op.drop_index(batch_op.f('ix_opportunities_server'))
        batch_op.drop_index(batch_op.f('ix_opportunities_bar_close_at'))

    op.drop_table('opportunities')
    # ### end Alembic commands ###
