"""phase6c shadow trades

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-04 12:12:16.263546
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0012'
down_revision: str | None = '0011'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadow_trades',
    sa.Column('shadow_id', sa.String(length=96), nullable=False),
    sa.Column('opportunity_id', sa.String(length=80), nullable=False),
    sa.Column('variant', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('server', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('session', sa.String(length=24), nullable=False),
    sa.Column('setup_strength', sa.Float(), nullable=False),
    sa.Column('rr', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('atr', sa.Float(), nullable=True),
    sa.Column('alerted', sa.Boolean(), nullable=False),
    sa.Column('followed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('signal_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('entry_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('spread_points', sa.Float(), nullable=True),
    sa.Column('slippage_points', sa.Float(), nullable=False),
    sa.Column('initial_sl', sa.Float(), nullable=False),
    sa.Column('sl', sa.Float(), nullable=False),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('stop_kind', sa.String(length=8), nullable=False),
    sa.Column('deadline', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('cursor', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('lot', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('mfe', sa.Float(), nullable=False),
    sa.Column('exit_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=8), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('r_net', sa.Float(), nullable=True),
    sa.Column('mae_r', sa.Float(), nullable=True),
    sa.Column('mfe_r', sa.Float(), nullable=True),
    sa.Column('gross_pnl', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.Column('net_pnl', sa.Float(), nullable=True),
    sa.Column('risk_money', sa.Float(), nullable=True),
    sa.Column('swap_days', sa.Integer(), nullable=False),
    sa.Column('flags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('shadow_id', name=op.f('pk_shadow_trades'))
    )
    with op.batch_alter_table('shadow_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shadow_trades_exit_at'), ['exit_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_trades_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_trades_server'), ['server'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_trades_signal_at'), ['signal_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_trades_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_shadow_trades_symbol'), ['symbol'], unique=False)

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alerted_at', app.storage.types.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('bid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ask', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quote_at', app.storage.types.UTCDateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('quote_at')
        batch_op.drop_column('ask')
        batch_op.drop_column('bid')
        batch_op.drop_column('alerted_at')

    with op.batch_alter_table('shadow_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shadow_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_shadow_trades_status'))
        batch_op.drop_index(batch_op.f('ix_shadow_trades_source'))
        batch_op.drop_index(batch_op.f('ix_shadow_trades_signal_at'))
        batch_op.drop_index(batch_op.f('ix_shadow_trades_server'))
        batch_op.drop_index(batch_op.f('ix_shadow_trades_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_shadow_trades_exit_at'))

    op.drop_table('shadow_trades')
    # ### end Alembic commands ###
