"""phase6c calibration

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-04 13:21:32.652983
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0013'
down_revision: str | None = '0012'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_tables',
    sa.Column('version', sa.String(length=48), nullable=False),
    sa.Column('server', sa.String(length=64), nullable=False),
    sa.Column('built_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('variant', sa.String(length=8), nullable=False),
    sa.Column('n_live', sa.Integer(), nullable=False),
    sa.Column('n_replay', sa.Integer(), nullable=False),
    sa.Column('window_start', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('window_end', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cells', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cv', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('uses_evidence', sa.Boolean(), nullable=False),
    sa.Column('brier', sa.Float(), nullable=True),
    sa.Column('reliability', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('pk_calibration_tables'))
    )
    with op.batch_alter_table('calibration_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calibration_tables_built_at'), ['built_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calibration_tables_server'), ['server'], unique=False)

    op.create_table('evidence_model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=48), nullable=False),
    sa.Column('server', sa.String(length=64), nullable=False),
    sa.Column('built_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('pooled', sa.Boolean(), nullable=False),
    sa.Column('group_key', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('names', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('coef', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('means', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('active', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('l2', sa.Float(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_model_versions'))
    )
    with op.batch_alter_table('evidence_model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_model_versions_version'), ['version'], unique=False)

    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calibration_version', sa.String(length=48), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('calibration_version')

    with op.batch_alter_table('evidence_model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_model_versions_version'))

    op.drop_table('evidence_model_versions')
    with op.batch_alter_table('calibration_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calibration_tables_server'))
        batch_op.drop_index(batch_op.f('ix_calibration_tables_built_at'))

    op.drop_table('calibration_tables')
    # ### end Alembic commands ###
