"""phase7 ingest nonces

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-04 13:44:51.264767
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0014'
down_revision: str | None = '0013'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_nonces',
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', 'nonce', name=op.f('pk_ingest_nonces'))
    )
    with op.batch_alter_table('ingest_nonces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_nonces_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingest_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_nonces_expires_at'))

    op.drop_table('ingest_nonces')
    # ### end Alembic commands ###
