"""phase7 outbox

Revision ID: 0015
Revises: 0014
Create Date: 2026-10-04 13:48:20.288009
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0015'
down_revision: str | None = '0014'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('occurred_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('coalesce_key', sa.String(length=96), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('sent_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_outbox_events'))
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_coalesce_key'), ['coalesce_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_type'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_sent_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_priority'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_coalesce_key'))

    op.drop_table('outbox_events')
    # ### end Alembic commands ###
