"""phase7 commands

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-04 14:17:40.796508
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0016'
down_revision: str | None = '0015'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_log',
    sa.Column('command_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('expires_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('received_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('totp_step', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('command_id', name=op.f('pk_command_log'))
    )
    with op.batch_alter_table('command_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_command_log_received_at'), ['received_at'], unique=False)

    op.create_table('engine_commands',
    sa.Column('command_id', sa.String(length=36), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('expires_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('totp', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('delivered_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('command_id', name=op.f('pk_engine_commands'))
    )
    with op.batch_alter_table('engine_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engine_commands_engine_id'), ['engine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_commands_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_engine_commands_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engine_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engine_commands_status'))
        batch_op.drop_index(batch_op.f('ix_engine_commands_expires_at'))
        batch_op.drop_index(batch_op.f('ix_engine_commands_engine_id'))

    op.drop_table('engine_commands')
    with op.batch_alter_table('command_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_command_log_received_at'))

    op.drop_table('command_log')
    # ### end Alembic commands ###
