"""phase7 ingest replicas

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-04 15:26:02.759267
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0018'
down_revision: str | None = '0017'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_replicas',
    sa.Column('chain', sa.String(length=64), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('verified_seq', sa.Integer(), nullable=False),
    sa.Column('verified_hash', sa.String(length=64), nullable=False),
    sa.Column('max_seq', sa.Integer(), nullable=False),
    sa.Column('first_bad_seq', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chain', name=op.f('pk_audit_replicas'))
    )
    op.create_table('replica_versions',
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('entity_key', sa.String(length=160), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('received_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', 'type', 'entity_key', name=op.f('pk_replica_versions'))
    )
    with op.batch_alter_table('replica_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_replica_versions_received_at'), ['received_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replica_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replica_versions_received_at'))

    op.drop_table('replica_versions')
    op.drop_table('audit_replicas')
    # ### end Alembic commands ###
