"""rev4 engine registry

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-04 17:17:37.538735
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0019'
down_revision: str | None = '0018'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engines',
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=False),
    sa.Column('previous_secret_enc', sa.Text(), nullable=True),
    sa.Column('previous_until', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('rotated_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('first_seen_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('last_seen_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_engines_owner_user_id_users')),
    sa.PrimaryKeyConstraint('engine_id', name=op.f('pk_engines'))
    )
    with op.batch_alter_table('engines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engines_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engines_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engines_status'))
        batch_op.drop_index(batch_op.f('ix_engines_owner_user_id'))

    op.drop_table('engines')
    # ### end Alembic commands ###
