"""stream events (TAA-804)

Cloud-only change feed behind the PWA's live stream: ``stream_heads`` (the last sequence number per engine)
and ``stream_events`` (one row per streamed replica change, keyed by engine and sequence number).

Revision ID: 0022
Revises: 0021
Create Date: 2026-10-04 18:31:26.126182
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0022'
down_revision: str | None = '0021'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_events',
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('topic', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('entity_key', sa.String(length=160), nullable=False),
    sa.Column('item', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', 'seq', name=op.f('pk_stream_events'))
    )
    op.create_table('stream_heads',
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', name=op.f('pk_stream_heads'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stream_heads')
    op.drop_table('stream_events')
    # ### end Alembic commands ###
