"""worker jobs (TAA-808)

Cloud worker tables: the job queue (`worker_jobs`), periodic schedules (`worker_schedules`) and worker
heartbeats (`worker_heartbeats`).

Revision ID: 0023
Revises: 0022
Create Date: 2026-10-04 18:57:39.265914
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0023'
down_revision: str | None = '0022'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=64), nullable=False),
    sa.Column('host', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('started_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('beat_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('jobs_done', sa.Integer(), nullable=False),
    sa.Column('jobs_failed', sa.Integer(), nullable=False),
    sa.Column('current_job', sa.String(length=36), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id', name=op.f('pk_worker_heartbeats'))
    )
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_heartbeats_beat_at'), ['beat_at'], unique=False)

    op.create_table('worker_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=True),
    sa.Column('run_after', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('lease_until', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('started_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('finished_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('job_id', name=op.f('pk_worker_jobs'))
    )
    with op.batch_alter_table('worker_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_jobs_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_jobs_finished_at'), ['finished_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_worker_jobs_status'), ['status'], unique=False)

    op.create_table('worker_schedules',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('next_run_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('last_run_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=8), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_worker_schedules'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_schedules')
    with op.batch_alter_table('worker_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_worker_jobs_run_after'))
        batch_op.drop_index(batch_op.f('ix_worker_jobs_kind'))
        batch_op.drop_index(batch_op.f('ix_worker_jobs_finished_at'))
        batch_op.drop_index(batch_op.f('ix_worker_jobs_dedupe_key'))

    op.drop_table('worker_jobs')
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_heartbeats_beat_at'))

    op.drop_table('worker_heartbeats')
    # ### end Alembic commands ###
