"""engine heartbeats and notifications (TAA-705)

Cloud-only: `engine_heartbeats` (newest heartbeat per engine plus the watchdog verdict) and `notifications`
(per-user notification records; Web Push delivers them from `push_status`, TAA-806).

Revision ID: 0024
Revises: 0023
Create Date: 2026-10-04 19:15:09.736182
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0024'
down_revision: str | None = '0023'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_heartbeats',
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('received_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('sent_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('market_open', sa.Boolean(), nullable=False),
    sa.Column('market_change_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('watch_status', sa.String(length=8), nullable=False),
    sa.Column('offline_since', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('offline_reason', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', name=op.f('pk_engine_heartbeats'))
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('read_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('push_status', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_engine_id'), ['engine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_push_status'), ['push_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_push_status'))
        batch_op.drop_index(batch_op.f('ix_notifications_engine_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    op.drop_table('engine_heartbeats')
    # ### end Alembic commands ###
