"""push subscriptions (TAA-806)

Cloud-only Web Push tables: `push_subscriptions` (one row per browser endpoint) and `notification_prefs`
(the notification types a user does not want pushed).

Revision ID: 0025
Revises: 0024
Create Date: 2026-10-04 19:30:23.120435
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0025'
down_revision: str | None = '0024'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_prefs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('disabled_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_notification_prefs'))
    )
    op.create_table('push_subscriptions',
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=2048), nullable=False),
    sa.Column('p256dh', sa.String(length=128), nullable=False),
    sa.Column('auth', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('last_success_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('last_failure_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('disabled_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subscription_id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))

    op.drop_table('push_subscriptions')
    op.drop_table('notification_prefs')
    # ### end Alembic commands ###
