"""backtest runs (TAA-807)

Cloud-only `backtest_runs`: a user's backtest request on an engine's uploaded history, its job state and its
results (summary, downsampled equity, stored trades).

Revision ID: 0026
Revises: 0025
Create Date: 2026-10-04 19:46:06.682084
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0026'
down_revision: str | None = '0025'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('preset', sa.String(length=32), nullable=False),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('started_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('finished_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('equity', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('trades', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('trades_total', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_backtest_runs'))
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_runs_engine_id'), ['engine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_runs_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_runs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_status'))
        batch_op.drop_index(batch_op.f('ix_backtest_runs_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_runs_engine_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_runs_created_at'))

    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
