"""user advisory prefs (TAA-809)

Cloud-only `user_advisory_prefs`: one validated advisory preference document per user (watchlists, alerts,
theories, trading profile, entry plan).

Revision ID: 0027
Revises: 0026
Create Date: 2026-10-04 20:04:13.707603
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0027'
down_revision: str | None = '0026'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_advisory_prefs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('prefs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_advisory_prefs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_advisory_prefs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_advisory_prefs')
    # ### end Alembic commands ###
