"""opportunity alerts (TAA-810)

Cloud-only `opportunity_alerts`: which opportunities each user was alerted to, for the personalizer's rate
limits and badge count and the silent same-tag replacement when an opportunity ends.

Revision ID: 0028
Revises: 0027
Create Date: 2026-10-04 20:21:15.448056
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0028'
down_revision: str | None = '0027'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_alerts',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('engine_id', sa.String(length=64), nullable=False),
    sa.Column('opportunity_id', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('sent_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('valid_until', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('final_status', sa.String(length=16), nullable=False),
    sa.Column('replaced_at', app.storage.types.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'engine_id', 'opportunity_id', name=op.f('pk_opportunity_alerts'))
    )
    with op.batch_alter_table('opportunity_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_alerts_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_alerts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_opportunity_alerts_sent_at'))

    op.drop_table('opportunity_alerts')
    # ### end Alembic commands ###
