"""plans and entitlements (TAA-8A2)

Cloud-only structure for plans: `plans`, `subscriptions` (manual assignment; billing is disabled),
`entitlement_overrides` and `usage_counters`. The plans themselves are seeded by the services at start.

Revision ID: 0029
Revises: 0028
Create Date: 2026-10-04 21:03:46.251011
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0029'
down_revision: str | None = '0028'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name_th', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_plans'))
    )
    op.create_table('entitlement_overrides',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entitlement_overrides_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key', name=op.f('pk_entitlement_overrides'))
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('period_end', app.storage.types.UTCDateTime(), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_ref', sa.String(length=128), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['plans.code'], name=op.f('fk_subscriptions_plan_code_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscription_id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('usage_counters',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_counters_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'key', 'period', name=op.f('pk_usage_counters'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_counters')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))

    op.drop_table('subscriptions')
    op.drop_table('entitlement_overrides')
    op.drop_table('plans')
    # ### end Alembic commands ###
