"""per-user alert sizing (TAA-8A4)

`opportunity_alerts` gains the user's own lot, risk money and currency at alert time and the theory
selection the alert was evaluated with (per-user accuracy: P/L = R x the user's risk money). Existing rows
get an empty currency and selection.

Revision ID: 0031
Revises: 0030
Create Date: 2026-10-04 23:06:23.289509
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0031'
down_revision: str | None = '0030'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('risk_money', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=8), server_default='', nullable=False))
        batch_op.add_column(sa.Column('selection', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_alerts', schema=None) as batch_op:
        batch_op.drop_column('selection')
        batch_op.drop_column('currency')
        batch_op.drop_column('risk_money')
        batch_op.drop_column('lot')

    # ### end Alembic commands ###
