"""billing events (TAA-8A5)

Cloud-only `billing_events`: applied billing-provider webhook events, so a replay changes nothing. Billing
itself stays disabled (`SUBSCRIPTIONS_ENABLED=false`).

Revision ID: 0032
Revises: 0031
Create Date: 2026-10-04 23:21:12.814077
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0032'
down_revision: str | None = '0031'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('received_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_billing_events'))
    )
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_events_user_id'))

    op.drop_table('billing_events')
    # ### end Alembic commands ###
