"""decision risk source (TAA-710)

`decision_records.risk_source` / `risk_percent`: which limits a decision was measured against (the engine
owner's trading profile from the cloud, its cached copy, or the local profile) and the effective per-trade risk.

Revision ID: 0033
Revises: 0032
Create Date: 2026-10-05 22:33:44.847627
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0033'
down_revision: str | None = '0032'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_source', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('risk_percent', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('decision_records', schema=None) as batch_op:
        batch_op.drop_column('risk_percent')
        batch_op.drop_column('risk_source')

    # ### end Alembic commands ###
