"""manual trade links (TAA-1006)

`manual_trade_links`: which signal a manual MT5 position followed, matched once by the engine and replicated.

Revision ID: 0034
Revises: 0033
Create Date: 2026-10-05 23:49:27.526958
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0034'
down_revision: str | None = '0033'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_trade_links',
    sa.Column('engine_id', sa.String(length=64), server_default='local', nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('ticket', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('price_open', sa.Float(), nullable=False),
    sa.Column('opened_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('signal_key', sa.String(length=64), nullable=True),
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('decision_id', sa.String(length=64), nullable=True),
    sa.Column('opportunity_id', sa.String(length=64), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('distance_r', sa.Float(), nullable=True),
    sa.Column('candidates', sa.Integer(), nullable=False),
    sa.Column('rule_version', sa.String(length=8), nullable=False),
    sa.Column('matched_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', 'position_id', name=op.f('pk_manual_trade_links'))
    )
    with op.batch_alter_table('manual_trade_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_trade_links_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_manual_trade_links_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_trade_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_trade_links_symbol'))
        batch_op.drop_index(batch_op.f('ix_manual_trade_links_opened_at'))

    op.drop_table('manual_trade_links')
    # ### end Alembic commands ###
