"""manual trade closes (TAA-1006 part 2)

The initial stop and the close (price, net profit, R) of each linked manual trade, from the MT5 deals.

Revision ID: 0035
Revises: 0034
Create Date: 2026-10-06 00:03:13.085210
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0035'
down_revision: str | None = '0034'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_trade_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sl_initial', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=8), server_default='OPEN', nullable=False))
        batch_op.add_column(sa.Column('closed_at', app.storage.types.UTCDateTime(), nullable=True))
        batch_op.add_column(sa.Column('close_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('net_profit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('r_multiple', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_trade_links', schema=None) as batch_op:
        batch_op.drop_column('r_multiple')
        batch_op.drop_column('net_profit')
        batch_op.drop_column('close_price')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('status')
        batch_op.drop_column('sl_initial')

    # ### end Alembic commands ###
