"""manual trade overrides (TAA-1006 part 2)

Cloud-only `manual_trade_overrides`: the owner's correction of a manual-trade link.

Revision ID: 0036
Revises: 0035
Create Date: 2026-10-06 00:06:29.150126
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0036'
down_revision: str | None = '0035'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_trade_overrides',
    sa.Column('engine_id', sa.String(length=64), server_default='local', nullable=False),
    sa.Column('position_id', sa.BigInteger(), nullable=False),
    sa.Column('choice', sa.String(length=16), nullable=False),
    sa.Column('signal_key', sa.String(length=64), nullable=True),
    sa.Column('strategy', sa.String(length=64), nullable=True),
    sa.Column('decision_id', sa.String(length=64), nullable=True),
    sa.Column('opportunity_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('updated_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', 'position_id', name=op.f('pk_manual_trade_overrides'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_trade_overrides')
    # ### end Alembic commands ###
