"""ai assessments (TAA-1303)

`ai_assessments`: every AI review of a proposed entry, answered or not (replicated).

Revision ID: 0037
Revises: 0036
Create Date: 2026-10-06 03:29:36.341873
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0037'
down_revision: str | None = '0036'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assessments',
    sa.Column('engine_id', sa.String(length=64), server_default='local', nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('signal_key', sa.String(length=80), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('bar_close_utc', sa.String(length=40), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('effect', sa.String(length=10), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', 'assessment_id', name=op.f('pk_ai_assessments'))
    )
    with op.batch_alter_table('ai_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_assessments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_assessments_signal_key'), ['signal_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_assessments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_assessments_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_assessments_symbol'))
        batch_op.drop_index(batch_op.f('ix_ai_assessments_status'))
        batch_op.drop_index(batch_op.f('ix_ai_assessments_signal_key'))
        batch_op.drop_index(batch_op.f('ix_ai_assessments_created_at'))

    op.drop_table('ai_assessments')
    # ### end Alembic commands ###
