"""magic registry

Revision ID: 0038
Revises: 0037
Create Date: 2026-10-06 04:04:33.884628
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = "0038"
down_revision: str | None = "0037"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "magic_registry",
        sa.Column("bot_id", sa.String(length=32), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("bot_slot", sa.Integer(), nullable=False),
        sa.Column("strategy_slot", sa.Integer(), nullable=False),
        sa.Column("assigned_at", app.storage.types.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("bot_id", "strategy", name=op.f("pk_magic_registry")),
        sa.UniqueConstraint("bot_slot", "strategy_slot", name=op.f("uq_magic_registry_bot_slot")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("magic_registry")
    # ### end Alembic commands ###
