"""manual stop history

Revision ID: 0039
Revises: 0038
Create Date: 2026-10-06 12:03:24.667134
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0039'
down_revision: str | None = '0038'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_trade_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stop_history', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manual_trade_links', schema=None) as batch_op:
        batch_op.drop_column('stop_history')

    # ### end Alembic commands ###
