"""ai notes

Revision ID: 0040
Revises: 0039
Create Date: 2026-10-06 13:00:32.724242
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = '0040'
down_revision: str | None = '0039'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_notes',
    sa.Column('engine_id', sa.String(length=64), server_default='local', nullable=False),
    sa.Column('note_id', sa.String(length=140), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('created_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_th', sa.Text(), nullable=False),
    sa.Column('facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', 'note_id', name=op.f('pk_ai_notes'))
    )
    with op.batch_alter_table('ai_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_notes_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_notes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_notes_subject'), ['subject'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_notes_subject'))
        batch_op.drop_index(batch_op.f('ix_ai_notes_status'))
        batch_op.drop_index(batch_op.f('ix_ai_notes_kind'))
        batch_op.drop_index(batch_op.f('ix_ai_notes_created_at'))

    op.drop_table('ai_notes')
    # ### end Alembic commands ###
