"""entry plan intents

Revision ID: 0041
Revises: 0040
Create Date: 2026-10-06 17:03:12.701385
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0041'
down_revision: str | None = '0040'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_intents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_key', sa.String(length=80), server_default='', nullable=False))
        batch_op.add_column(sa.Column('part_index', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('order_type', sa.String(length=8), server_default='MARKET', nullable=False))
        batch_op.add_column(sa.Column('limit_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cancel_after', app.storage.types.UTCDateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_intents_plan_key'), ['plan_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_intents_plan_key'))
        batch_op.drop_column('cancel_after')
        batch_op.drop_column('limit_price')
        batch_op.drop_column('order_type')
        batch_op.drop_column('part_index')
        batch_op.drop_column('plan_key')

    # ### end Alembic commands ###
