"""broker trades

`broker_trades`: closed bot positions on the broker account (DEMO/LIVE), booked from the MT5 deals (TAA-1208).

Revision ID: 0042
Revises: 0041
Create Date: 2026-10-07 15:40:36.630901
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.storage.types
from sqlalchemy import Text


revision: str = '0042'
down_revision: str | None = '0041'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_trades',
    sa.Column('engine_id', sa.String(length=64), server_default='local', nullable=False),
    sa.Column('position_ticket', sa.BigInteger(), nullable=False),
    sa.Column('account_key', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('magic', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('plan_key', sa.String(length=80), nullable=False),
    sa.Column('part_index', sa.Integer(), nullable=False),
    sa.Column('entry_time', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('sl_initial', sa.Float(), nullable=False),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('exit_time', app.storage.types.UTCDateTime(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.String(length=16), nullable=True),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('swap', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('net', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('booked_at', app.storage.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('engine_id', 'position_ticket', name=op.f('pk_broker_trades'))
    )
    with op.batch_alter_table('broker_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broker_trades_account_key'), ['account_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_broker_trades_exit_time'), ['exit_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_broker_trades_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broker_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_broker_trades_exit_time'))
        batch_op.drop_index(batch_op.f('ix_broker_trades_account_key'))

    op.drop_table('broker_trades')
    # ### end Alembic commands ###
