<#
.SYNOPSIS
    Starts the local TAA demo stack: web (API + PWA), worker and a PAPER engine on FakeMT5, then opens the browser.

.DESCRIPTION
    Development and demonstration only. Nothing here touches a broker account: the engine runs PAPER on the
    in-memory FakeMT5, with its own database (data\demo\engine.db) and its own engine id, so demo rows never mix
    with the real engine or data\taa_engine.db.

    Each part opens in its own PowerShell window (close a window or press Ctrl+C there to stop that part):
      - web     python -m app.web      http://127.0.0.1:8000
      - worker  python -m app.worker   runs backtests and the other cloud jobs
      - engine  python -m app.main --mode paper --fake, syncing to the local web

    The demo engine's id and HMAC secret live in .env.demo (git-ignored). Create it once with -Setup, which
    registers a new engine for the given web user (the secret is written to the file, never printed):
        scripts\start-demo.ps1 -Setup -Owner aomkuma

    The engine gets a copy of config.yaml with sync.enabled: true (data\demo\config.demo.yaml), rebuilt at every
    start so it follows config.yaml.

.EXAMPLE
    scripts\start-demo.cmd                       (double-click: same as below)
    powershell -NoProfile -ExecutionPolicy Bypass -File scripts\start-demo.ps1
    powershell -NoProfile -ExecutionPolicy Bypass -File scripts\start-demo.ps1 -NoEngine
#>
[CmdletBinding()]
param(
    [switch]$Setup,
    [string]$Owner = "",
    [switch]$NoEngine,
    [switch]$NoBrowser,
    # internal: the child windows call this script again with one role
    [ValidateSet("", "web", "worker", "engine")]
    [string]$Role = ""
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Python = Join-Path $Root ".venv\Scripts\python.exe"
$DemoEnv = Join-Path $Root ".env.demo"
$DemoDir = Join-Path $Root "data\demo"
$WebUrl = "http://127.0.0.1:8000"
Set-Location $Root

function Fail([string]$message) {
    Write-Host "error: $message" -ForegroundColor Red
    exit 1
}

function Read-DemoEnv {
    if (-not (Test-Path $DemoEnv)) {
        Fail ".env.demo not found. Create it once: scripts\start-demo.ps1 -Setup -Owner <web user>"
    }
    $values = @{}
    foreach ($line in Get-Content $DemoEnv) {
        $text = $line.Trim()
        if ($text -eq "" -or $text.StartsWith("#")) { continue }
        $at = $text.IndexOf("=")
        if ($at -lt 1) { continue }
        $values[$text.Substring(0, $at).Trim()] = $text.Substring($at + 1).Trim()
    }
    foreach ($key in @("ENGINE_ID", "ENGINE_HMAC_SECRET")) {
        if (-not $values.ContainsKey($key) -or $values[$key] -eq "") { Fail ".env.demo has no $key" }
    }
    return $values
}

function Write-DemoConfig {
    New-Item -ItemType Directory -Force -Path $DemoDir | Out-Null
    $source = Get-Content (Join-Path $Root "config.yaml") -Raw
    $pattern = "(?m)^(sync:\r?\n\s+enabled:\s*)false"
    if ($source -notmatch $pattern) { Fail "config.yaml: could not find 'sync: enabled: false' to switch on" }
    $target = Join-Path $DemoDir "config.demo.yaml"
    $header = "# Generated by scripts\start-demo.ps1 from config.yaml at every start; edit config.yaml instead.`r`n"
    [System.IO.File]::WriteAllText($target, $header + ($source -replace $pattern, '${1}true'))
    return $target
}

# --- one part, inside its own window ------------------------------------------------------------------------
if ($Role -ne "") {
    $Host.UI.RawUI.WindowTitle = "TAA demo - $Role"
    switch ($Role) {
        "web" { & $Python -m app.web }
        "worker" { & $Python -m app.worker }
        "engine" {
            $values = Read-DemoEnv
            $config = Write-DemoConfig
            $dbPath = (Join-Path $DemoDir "engine.db") -replace "\\", "/"
            # process variables override .env (the MT5 and safety settings still come from there)
            $env:ENGINE_ID = $values["ENGINE_ID"]
            $env:ENGINE_HMAC_SECRET = $values["ENGINE_HMAC_SECRET"]
            $env:CLOUD_BASE_URL = $WebUrl
            $env:ENGINE_DB_URL = "sqlite:///$dbPath"
            $env:CONFIG_FILE = $config
            $env:TRADING_MODE = "PAPER"
            & $Python -m app.main --mode paper --fake
        }
    }
    Write-Host ""
    Write-Host "$Role stopped (exit code $LASTEXITCODE). Close this window." -ForegroundColor Yellow
    exit $LASTEXITCODE
}

if (-not (Test-Path $Python)) { Fail "no virtual environment at .venv (see CLAUDE.md: setup)" }

# --- one-time setup: register a demo engine and write .env.demo ---------------------------------------------
if ($Setup) {
    if ($Owner -eq "") { Fail "-Setup needs -Owner <web user> (see: python -m app.cli web list-users)" }
    if (Test-Path $DemoEnv) { Fail ".env.demo already exists; delete it first to register a new demo engine" }
    $output = & $Python -m app.cli web engine add --owner $Owner --label "fake demo" 2>&1 | Out-String
    if ($LASTEXITCODE -ne 0) { Fail "could not register the demo engine:`n$output" }
    $id = [regex]::Match($output, "(?m)^ENGINE_ID=(\S+)").Groups[1].Value
    $secret = [regex]::Match($output, "(?m)^ENGINE_HMAC_SECRET=(\S+)").Groups[1].Value
    if ($id -eq "" -or $secret -eq "") { Fail "unexpected output from 'web engine add'" }
    $lines = @(
        "# TAA demo engine (FakeMT5, PAPER) for scripts\start-demo.ps1. Git-ignored; keep it private.",
        "# Revoke: python -m app.cli web engine revoke $id --confirm $id",
        "ENGINE_ID=$id",
        "ENGINE_HMAC_SECRET=$secret"
    )
    [System.IO.File]::WriteAllLines($DemoEnv, $lines)
    Write-Host "Demo engine $id registered for $Owner; .env.demo written." -ForegroundColor Green
    exit 0
}

# --- start everything ---------------------------------------------------------------------------------------
if (-not (Test-Path (Join-Path $Root "frontend\dist\index.html"))) {
    Write-Host "warning: frontend\dist is missing; build it first: cd frontend; npm run build" -ForegroundColor Yellow
}
if (-not $NoEngine) { Read-DemoEnv | Out-Null }

function Start-Part([string]$part) {
    $script = Join-Path $PSScriptRoot "start-demo.ps1"
    Start-Process powershell -ArgumentList @("-NoProfile", "-ExecutionPolicy", "Bypass", "-NoExit", "-File", "`"$script`"", "-Role", $part) | Out-Null
}

function Test-Web {
    try {
        $response = Invoke-WebRequest -UseBasicParsing -TimeoutSec 2 -Uri "$WebUrl/api/v1/health"
        return $response.StatusCode -eq 200
    } catch {
        return $false
    }
}

if (Test-Web) {
    Write-Host "The web service already answers on $WebUrl; not starting another one."
} else {
    Start-Part "web"
}
Start-Part "worker"

Write-Host -NoNewline "Waiting for the web service"
$ready = $false
for ($i = 0; $i -lt 60; $i++) {
    if (Test-Web) { $ready = $true; break }
    Write-Host -NoNewline "."
    Start-Sleep -Seconds 1
}
Write-Host ""
if (-not $ready) { Fail "the web service did not answer within 60 s; look at the 'TAA demo - web' window" }

if (-not $NoEngine) { Start-Part "engine" }
if (-not $NoBrowser) { Start-Process $WebUrl }

Write-Host "TAA demo is running: $WebUrl" -ForegroundColor Green
Write-Host "Stop it by closing the 'TAA demo - ...' windows (or Ctrl+C in each)."
