<#
.SYNOPSIS
    Starts the local TAA demo stack: web (API + PWA), worker and a PAPER engine on FakeMT5, then opens the browser.

.DESCRIPTION
    Development and demonstration only. Nothing here touches a broker account: the engine runs PAPER on the
    in-memory FakeMT5, with its own database (data\demo\engine.db) and its own engine id, so demo rows never mix
    with the real engine or data\taa_engine.db.

    Each part opens in its own PowerShell window (close a window or press Ctrl+C there to stop that part):
      - web     python -m app.web      http://127.0.0.1:8000
      - worker  python -m app.worker   runs backtests and the other cloud jobs
      - engine  python -m app.main --mode paper --fake, syncing to the local web

    The demo engine's id and HMAC secret live in .env.demo (git-ignored). Create it once with -Setup, which
    registers a new engine for the given web user (the secret is written to the file, never printed):
        scripts\start-demo.ps1 -Setup -Owner aomkuma

    The engine gets a copy of config.yaml with sync.enabled: true (data\demo\config.demo.yaml), rebuilt at every
    start so it follows config.yaml.

    -Mt5 runs the engine on the real MT5 terminal from .env (MT5_* settings, e.g. the FBS demo account) instead
    of FakeMT5, so the charts show real broker prices. It is still PAPER (forced here): no broker orders.
    The web service allows one active engine per deployment, so this mode is a second deployment with its own
    web database (data\demo\cloud-mt5.db), engine database (data\demo\engine-mt5.db) and engine id
    (.env.demo-mt5), served on http://localhost:8001 (another host than 127.0.0.1:8000, so the two logins keep
    separate cookies and both stacks can run at once). -Setup -Mt5 creates the web user there (password and
    TOTP, interactive) if it does not exist yet, then registers the engine. Check the terminal first with:
    python -m app.cli doctor

.EXAMPLE
    scripts\start-demo.cmd                       (double-click: same as below)
    powershell -NoProfile -ExecutionPolicy Bypass -File scripts\start-demo.ps1
    powershell -NoProfile -ExecutionPolicy Bypass -File scripts\start-demo.ps1 -NoEngine
    scripts\start-demo.cmd -Setup -Mt5 -Owner aomkuma    (once)
    scripts\start-demo.cmd -Mt5                          (real MT5 prices, PAPER)
#>
[CmdletBinding()]
param(
    [switch]$Setup,
    [string]$Owner = "",
    [switch]$NoEngine,
    [switch]$NoBrowser,
    [switch]$Mt5,
    # internal: the child windows call this script again with one role
    [ValidateSet("", "web", "worker", "engine")]
    [string]$Role = ""
)

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $PSScriptRoot
$Python = Join-Path $Root ".venv\Scripts\python.exe"
$DemoEnv = Join-Path $Root $(if ($Mt5) { ".env.demo-mt5" } else { ".env.demo" })
$EngineLabel = $(if ($Mt5) { "mt5 demo (paper)" } else { "fake demo" })
$EngineDb = $(if ($Mt5) { "engine-mt5.db" } else { "engine.db" })
$DemoDir = Join-Path $Root "data\demo"
$WebUrl = $(if ($Mt5) { "http://localhost:8001" } else { "http://127.0.0.1:8000" })
Set-Location $Root

function Fail([string]$message) {
    Write-Host "error: $message" -ForegroundColor Red
    exit 1
}

function Read-DemoEnv {
    if (-not (Test-Path $DemoEnv)) {
        Fail "$(Split-Path -Leaf $DemoEnv) not found. Create it once: scripts\start-demo.ps1 -Setup$(if ($Mt5) { ' -Mt5' }) -Owner <web user>"
    }
    $values = @{}
    foreach ($line in Get-Content $DemoEnv) {
        $text = $line.Trim()
        if ($text -eq "" -or $text.StartsWith("#")) { continue }
        $at = $text.IndexOf("=")
        if ($at -lt 1) { continue }
        $values[$text.Substring(0, $at).Trim()] = $text.Substring($at + 1).Trim()
    }
    foreach ($key in @("ENGINE_ID", "ENGINE_HMAC_SECRET")) {
        if (-not $values.ContainsKey($key) -or $values[$key] -eq "") { Fail "$(Split-Path -Leaf $DemoEnv) has no $key" }
    }
    return $values
}

function Write-DemoConfig {
    New-Item -ItemType Directory -Force -Path $DemoDir | Out-Null
    $source = Get-Content (Join-Path $Root "config.yaml") -Raw
    $pattern = "(?m)^(sync:\r?\n\s+enabled:\s*)false"
    if ($source -notmatch $pattern) { Fail "config.yaml: could not find 'sync: enabled: false' to switch on" }
    $text = $source -replace $pattern, '${1}true'
    $target = Join-Path $DemoDir "config.demo.yaml"
    if ($Mt5) {
        # own health port and heartbeat file, so it can run next to the FakeMT5 engine
        $health = "(?m)^(\s+)health_port:\s*\d+"
        if ($text -notmatch $health) { Fail "config.yaml: could not find 'engine: health_port:'" }
        $text = $text -replace $health, "`${1}health_port: 8766`n`${1}heartbeat_file: data/demo/heartbeat-mt5.json"
        $target = Join-Path $DemoDir "config.demo-mt5.yaml"
    }
    $header = "# Generated by scripts\start-demo.ps1 from config.yaml at every start; edit config.yaml instead.`r`n"
    [System.IO.File]::WriteAllText($target, $header + $text)
    return $target
}

# The -Mt5 deployment: process variables override .env for web, worker and the web CLI.
if ($Mt5) {
    $env:DATABASE_URL = "sqlite:///data/demo/cloud-mt5.db"
    $env:PORT = "8001"
    $env:WEB_PUBLIC_ORIGIN = $WebUrl
}

# --- one part, inside its own window ------------------------------------------------------------------------
if ($Role -ne "") {
    $Host.UI.RawUI.WindowTitle = "TAA demo - $Role$(if ($Mt5 -and $Role -eq 'engine') { ' (MT5)' })"
    switch ($Role) {
        "web" { & $Python -m app.web }
        "worker" { & $Python -m app.worker }
        "engine" {
            $values = Read-DemoEnv
            $config = Write-DemoConfig
            $dbPath = (Join-Path $DemoDir $EngineDb) -replace "\\", "/"
            # process variables override .env (the MT5 and safety settings still come from there)
            $env:ENGINE_ID = $values["ENGINE_ID"]
            $env:ENGINE_HMAC_SECRET = $values["ENGINE_HMAC_SECRET"]
            $env:CLOUD_BASE_URL = $WebUrl
            $env:ENGINE_DB_URL = "sqlite:///$dbPath"
            $env:CONFIG_FILE = $config
            $env:TRADING_MODE = "PAPER"
            if ($Mt5) {
                # real terminal and account from .env; PAPER never sends broker orders
                & $Python -m app.main --mode paper
            } else {
                & $Python -m app.main --mode paper --fake
            }
        }
    }
    Write-Host ""
    Write-Host "$Role stopped (exit code $LASTEXITCODE). Close this window." -ForegroundColor Yellow
    exit $LASTEXITCODE
}

if (-not (Test-Path $Python)) { Fail "no virtual environment at .venv (see CLAUDE.md: setup)" }

# --- one-time setup: register a demo engine and write .env.demo ---------------------------------------------
if ($Setup) {
    if ($Owner -eq "") { Fail "-Setup needs -Owner <web user> (see: python -m app.cli web list-users)" }
    if (Test-Path $DemoEnv) {
        Fail "$(Split-Path -Leaf $DemoEnv) already exists; delete it first to register a new demo engine"
    }
    New-Item -ItemType Directory -Force -Path $DemoDir | Out-Null
    if ($Mt5) {
        $users = & $Python -m app.cli web list-users 2>&1 | Out-String
        if ($LASTEXITCODE -ne 0) { Fail "could not list the web users:`n$users" }
        if ($users -notmatch "(?m)^$([regex]::Escape($Owner))\s") {
            Write-Host "Creating web user $Owner in data\demo\cloud-mt5.db (password, then TOTP):"
            & $Python -m app.cli web create-user $Owner
            if ($LASTEXITCODE -ne 0) { Fail "could not create the web user $Owner" }
        }
    }
    $output = & $Python -m app.cli web engine add --owner $Owner --label $EngineLabel 2>&1 | Out-String
    if ($LASTEXITCODE -ne 0) { Fail "could not register the demo engine:`n$output" }
    $id = [regex]::Match($output, "(?m)^ENGINE_ID=(\S+)").Groups[1].Value
    $secret = [regex]::Match($output, "(?m)^ENGINE_HMAC_SECRET=(\S+)").Groups[1].Value
    if ($id -eq "" -or $secret -eq "") { Fail "unexpected output from 'web engine add'" }
    $lines = @(
        "# TAA demo engine ($EngineLabel) for scripts\start-demo.ps1. Git-ignored; keep it private.",
        "# Revoke: python -m app.cli web engine revoke $id --confirm $id",
        "ENGINE_ID=$id",
        "ENGINE_HMAC_SECRET=$secret"
    )
    [System.IO.File]::WriteAllLines($DemoEnv, $lines)
    Write-Host "Demo engine $id registered for $Owner; $(Split-Path -Leaf $DemoEnv) written." -ForegroundColor Green
    exit 0
}

# --- start everything ---------------------------------------------------------------------------------------
if (-not (Test-Path (Join-Path $Root "frontend\dist\index.html"))) {
    Write-Host "warning: frontend\dist is missing; build it first: cd frontend; npm run build" -ForegroundColor Yellow
}
if (-not $NoEngine) { Read-DemoEnv | Out-Null }

function Start-Part([string]$part) {
    $script = Join-Path $PSScriptRoot "start-demo.ps1"
    $arguments = @("-NoProfile", "-ExecutionPolicy", "Bypass", "-NoExit", "-File", "`"$script`"", "-Role", $part)
    if ($Mt5) { $arguments += "-Mt5" }
    Start-Process powershell -ArgumentList $arguments | Out-Null
}

function Test-Web {
    try {
        $response = Invoke-WebRequest -UseBasicParsing -TimeoutSec 2 -Uri "$WebUrl/api/v1/health"
        return $response.StatusCode -eq 200
    } catch {
        return $false
    }
}

if (Test-Web) {
    Write-Host "The web service already answers on $WebUrl; not starting another one."
} else {
    Start-Part "web"
}
Start-Part "worker"

Write-Host -NoNewline "Waiting for the web service"
$ready = $false
for ($i = 0; $i -lt 60; $i++) {
    if (Test-Web) { $ready = $true; break }
    Write-Host -NoNewline "."
    Start-Sleep -Seconds 1
}
Write-Host ""
if (-not $ready) { Fail "the web service did not answer within 60 s; look at the 'TAA demo - web' window" }

if (-not $NoEngine) { Start-Part "engine" }
if (-not $NoBrowser) { Start-Process $WebUrl }

Write-Host "TAA demo is running ($(if ($Mt5) { 'real MT5 terminal, PAPER' } else { 'FakeMT5, PAPER' })): $WebUrl" -ForegroundColor Green
Write-Host "Stop it by closing the 'TAA demo - ...' windows (or Ctrl+C in each)."
